trigger:
  tags:
    include:
      - 'v*'
  branches:
    include:
      - 'main'

pool: 'vmssagentpool'

steps:
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: 'GitVersion.yml'

  - script: |
      sudo mkdir -p /opt/hostedtoolcache/node/16.10.0/x64
      sudo chown -R $USER /opt/hostedtoolcache/node/16.10.0
    displayName: 'Node tool setup'

  - task: NodeTool@0
    inputs:
      versionSpec: '16.10.0'  

  - task: Npm@1
    displayName: NPM Ci
    inputs:
      command: custom
      customCommand: ci
  
  - task: Npm@1
    displayName: NPM Build
    inputs:
      command: custom
      customCommand: run build

  - task: Npm@1
    displayName: NPM Lint
    inputs:
      command: custom
      customCommand: run lint

  - task: Npm@1
    displayName: NPM Version
    inputs:
      workingDir: .
      command: custom
      customCommand: --no-git-tag-version version $(GitVersion.SemVer)

  - task: Npm@1
    displayName: NPM Local Publish
    condition: or(eq(variables['build.sourceBranch'], 'refs/heads/main'),startsWith(variables['build.sourceBranch'], 'refs/tags/v'))
    inputs:
      command: publish
      workingDir: .  
      publishRegistry: useFeed
      publishFeed: unleash

  - task: Npm@1
    displayName: NPM Global Publish
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')
    inputs:
      command: publish
      workingDir: .  
      publishRegistry: useExternalRegistry
      publishEndpoint: unleash-tech-global-feed
